// Generated by Wrangler on Thu Aug 08 2024 22:09:29 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	TOKENS: KVNamespace;
	NODE_VERSION: ">=21.1.0";
	ACCOUNTS: D1Database;
}
